name       : cherrytree
version    : 0.39.4
release    : 17
source     :
    - https://www.giuspen.com/software/cherrytree-0.39.4.tar.xz : 6db3d17c49dfd3c7d83ad2cc8b8be28350497566acfe827e6f178538669b4f76
homepage   : https://www.giuspen.com/cherrytree/
license    : GPL-3.0-or-later
component  : office.notes
summary    : A hierarchical note taking application
description: |
    A hierarchical note taking application, featuring rich text and syntax highlighting, storing data in a single xml or sqlite file.
builddeps  :
    - python-setuptools
rundeps    :
    - p7zip
    - pyenchant
    - pygtksourceview
    - python-chardet
    - python-dbus
setup      : |
    sed 's|.*subprocess.call("update-desktop-database").*|#&|g' -i setup.py
build      : |
    %python_setup
install    : |
    %python_install
