name       : cherrytree
version    : 0.39.2
release    : 16
source     :
    - https://github.com/giuspen/cherrytree/archive/0.39.2.tar.gz : d879c03c460558ffc1977e2dfed6cb14121c7bc6d64e6a79101e5a3bee3d42b0
homepage   : https://www.giuspen.com/cherrytree/
license    : GPL-3.0-or-later
component  : office.notes
summary    : A hierarchical note taking application
description: |
    A hierarchical note taking application, featuring rich text and syntax highlighting, storing data in a single xml or sqlite file.
builddeps  :
    - python-setuptools
rundeps    :
    - p7zip
    - pyenchant
    - pygtksourceview
    - python-chardet
    - python-dbus
setup      : |
    sed 's|.*subprocess.call("update-desktop-database").*|#&|g' -i setup.py
build      : |
    %python_setup
install    : |
    %python_install
