name       : cherrytree
version    : 0.38.10
release    : 14
source     :
    - https://github.com/giuspen/cherrytree/archive/0.38.10.tar.gz : 002801dd978550a84f75ab0bd4024ed89f2e82b72fb72f0ea889e33385b2d6b5
homepage   : https://www.giuspen.com/cherrytree/
license    : GPL-3.0-or-later
component  : office.notes
summary    : A hierarchical note taking application
description: |
    A hierarchical note taking application, featuring rich text and syntax highlighting, storing data in a single xml or sqlite file.
builddeps  :
    - python-setuptools
rundeps    :
    - p7zip
    - pyenchant
    - pygtksourceview
    - python-chardet
    - python-dbus
setup      : |
    sed 's|.*subprocess.call("update-desktop-database").*|#&|g' -i setup.py
build      : |
    %python_setup
install    : |
    %python_install
