name       : cherrytree
version    : 0.38.3
release    : 8
source     :
    - http://www.giuspen.com/software/cherrytree-0.38.3.tar.xz : 249ec9d6ec375275da430dff61762cda01fdfcf2fc252a005ce6063d5d46f2f9
license    : GPL-3.0
component  : office.notes
summary    : A heirarchical note taking application
description: |
    A hierarchical note taking application, featuring rich text and syntax highlighting, storing data in a single
    xml or sqlite file.
builddeps  :
    - pkgconfig(python2)
    - python-setuptools
rundeps    :
    - pyenchant
    - python-gtk2
    - pygtksourceview
    - python-gobject2
    - python-dbus
    - python-chardet
    - p7zip
setup      : |
    sed 's|.*subprocess.call("update-desktop-database").*|#&|g' -i setup.py
build      : |
    %python_setup
install    : |
    %python_install
