name       : cherrytree
version    : 0.38.0
release    : 6
source     :
    - http://www.giuspen.com/software/cherrytree-0.38.0.tar.xz : cbc691cdbc2859d3247c09ede23c4a64c76bc1257e7d10fe6197a77771d07d55
license    : GPL-3.0
component  : office.notes
summary    : A heirarchical note taking application
description: |
    A hierarchical note taking application, featuring rich text and syntax highlighting, storing data in a single
    xml or sqlite file.
builddeps  :
    - pkgconfig(python2)
    - python-setuptools
rundeps    :
    - pyenchant
    - python-gtk2
    - pygtksourceview
    - python-gobject2
    - python-dbus
    - python-chardet
    - p7zip
setup      : |
    sed 's|.*subprocess.call("update-desktop-database").*|#&|g' -i setup.py
build      : |
    %python_setup
install    : |
    %python_install
