name       : cherrytree
version    : 0.99.49
release    : 24
source     :
    - https://github.com/giuspen/cherrytree/releases/download/0.99.49/cherrytree_0.99.49.tar.xz : cb3f48903716c3dfca7b4638c57137642d99c76f1bfc2f5f9f5b442baff2cde1
homepage   : https://www.giuspen.com/cherrytree/
license    : GPL-3.0-or-later
component  : office.notes
summary    : A hierarchical note taking application
description: |
    cherrytree is a hierarchical note taking application, featuring rich text, syntax  highlighting, images handling, hyperlinks, import/export with support for multiple formats, support for multiple languages, and more.
builddeps  :
    - pkgconfig(fmt)
    - pkgconfig(gspell-1)
    - pkgconfig(gtksourceviewmm-3.0)
    - pkgconfig(libcurl)
    - pkgconfig(libxml++-2.6)
    - pkgconfig(spdlog)
    - pkgconfig(sqlite3)
    - pkgconfig(uchardet)
rundeps    :
    - p7zip
setup      : |
    %cmake -DBUILD_TESTING=OFF
build      : |
    %make
install    : |
    %make_install
