name       : cherrytree
version    : 0.37.5
release    : 3
source     :
    - https://github.com/giuspen/cherrytree/archive/0.37.5.tar.gz : 1e1201700fc07fc5ec527345c9b9c775b0eae9298bb7722e18b0e5b19dbdd220
license    : GPL-3.0
component  : office
summary    : A heirarchical note taking application
description: |
    A hierarchical note taking application, featuring rich text and syntax highlighting, storing data in a single
    xml or sqlite file.
builddeps  :
    - pkgconfig(python2)
    - python-setuptools
rundeps    :
    - python-gtk2
    - pygtksourceview
    - python-gobject2
    - python-dbus
    - python-chardet
    - p7zip
setup      : |
    sed 's|.*subprocess.call("update-desktop-database").*|#&|g' -i setup.py
build      : |
    %python_setup
install    : |
    %python_install
