name       : cherrytree
version    : 0.38.5
release    : 10
source     :
    - https://github.com/giuspen/cherrytree/archive/0.38.5.tar.gz : db409e1c330ff9d95eba5d57ffa174bdb004f1606fc9c1e5f12916c299fb52a9
license    : GPL-3.0
component  : office.notes
summary    : A heirarchical note taking application
description: |
    A hierarchical note taking application, featuring rich text and syntax highlighting, storing data in a single
    xml or sqlite file.
builddeps  :
    - pkgconfig(python2)
    - python-setuptools
rundeps    :
    - pyenchant
    - python-gtk2
    - pygtksourceview
    - python-gobject2
    - python-dbus
    - python-chardet
    - p7zip
setup      : |
    sed 's|.*subprocess.call("update-desktop-database").*|#&|g' -i setup.py
build      : |
    %python_setup
install    : |
    %python_install
