name       : cherrytree
version    : 0.39.0
release    : 15
source     :
    - https://github.com/giuspen/cherrytree/archive/0.39.0.tar.gz : e8f4b10166f8ba87dcf375e8146d1a3f491bffcf4d1dfd4f76e361c1a0bdcf2c
homepage   : https://www.giuspen.com/cherrytree/
license    : GPL-3.0-or-later
component  : office.notes
summary    : A hierarchical note taking application
description: |
    A hierarchical note taking application, featuring rich text and syntax highlighting, storing data in a single xml or sqlite file.
builddeps  :
    - python-setuptools
rundeps    :
    - p7zip
    - pyenchant
    - pygtksourceview
    - python-chardet
    - python-dbus
setup      : |
    sed 's|.*subprocess.call("update-desktop-database").*|#&|g' -i setup.py
build      : |
    %python_setup
install    : |
    %python_install
